// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://jekjxwkyhyohcjhhyius.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impla2p4d2t5aHlvaGNqaGh5aXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE0ODUyNzAsImV4cCI6MjA0NzA2MTI3MH0.f615WCdrf1tu3hlhY7_Y7gv0ncHvfvASfaCvNDWZ39c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);